/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aboud.gradleproject1;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Aboud Mahmoud
 */
public class AgentMenu extends javax.swing.JPanel {

    /**
     * Creates new form AgentMenu
     */
    private String[] headr = {"—ﬁ„ «·„⁄—›","«”„ «·⁄„Ì· ", "Õ’«·… «·⁄„Ì·", "⁄œœ ÿ—Êœ ", "«·„»·€ «·„ÿ·Ê» „‰ «·⁄„Ì·", "›—⁄ «· Õ’Ì·"};
    private String[][] dater;
    private ArrayList<PackgeValue> arr;
    private ArrayList<CoustmerInfo> arr2;

    public AgentMenu() throws MalformedURLException {
        initComponents();
getTheData();
seticonbutton();
    }
    private void seticonbutton() throws MalformedURLException
    {
        jButton1.setIcon(setIMAgeFor(ImagTakeUrl.edite));
        jButton2.setIcon(setIMAgeFor(ImagTakeUrl.refresh));
    }
    
     private ImageIcon setIMAgeFor(String path) throws MalformedURLException {
        URL urt = new URL(path);
        Image iconr = Toolkit.getDefaultToolkit().getImage(urt);
        ImageIcon myimage = new ImageIcon(iconr);
        return myimage;
    }

    void getTheData() {
        arr2 = LiteConection.getThe_Coustmerinfor();
        dater = new String[arr2.size()][6];
        for (int i = 0; i < arr2.size(); i++) {
              dater[i][0] = ""+ arr2.get(i).getCoustmerID();
            dater[i][1] = arr2.get(i).getCoustmerName();
            dater[i][2] = arr2.get(i).getCoustmerPays();
            dater[i][3] = "" + arr2.get(i).getNumberOfBackge();
            dater[i][4] = arr2.get(i).getCosutmerFees();
            dater[i][5] =  arr2.get(i).getDamerntOfCastmr();
             
        }
          jTable1=new JTable(dater,headr);
       
             ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer())
             .setHorizontalAlignment((int)JLabel.CENTER_ALIGNMENT);
     DefaultTableCellRenderer v = new DefaultTableCellRenderer();
     v.setHorizontalAlignment(JLabel.CENTER);
     jTable1.getColumnModel().getColumn(0).setCellRenderer(v);
     for( int i=0 ; i<jTable1.getColumnCount();i++)
     {
         jTable1.getColumnModel().getColumn(i).setCellRenderer(v);
     }
      jScrollPane1.setViewportView(jTable1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(42, 157, 143));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("⁄—÷");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(42, 157, 143));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(" ÕœÌÀ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int col= 0;
            int row=jTable1.getSelectedRow();
            String id=jTable1.getModel().getValueAt(row, col).toString();
            
            int ide=Integer.parseInt(id);
           EditAgent edir= new EditAgent(); 
           arr2=LiteConection.getThe_Coustmerinfor();
           for (int i=0 ; i <arr2.size(); i++)
           {
               if(arr2.get(i).getCoustmerID()==ide)
               {
                      try {
                       // ts.getTheData(arr.get(i).getOwnerPackageName(), arr.get(i).getPackageID(), arr.get(i).isPackgeDilverd(),arr.get(i).getPackgeDamperntHolder(), arr.get(i).getPackageSerilNumber(), arr.get(i).getPackgePrice(),arr.get(i).getOwnerPhoneNumber(),arr.get(i).getPackgeDate());
                       edir.getTheData(arr2.get(i).getCoustmerName(), arr2.get(i).getCoustmerPays(),arr2.get(i).getCosutmerFees()
                       ,arr2.get(i).getCoustmerID(),arr2.get(i).getDamerntOfCastmr());
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
                    }
               }
               edir.setVisible(true);
               break;
           }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            MangmentPage.jTabbedPane2.remove(this);
            MangmentPage.jTabbedPane2.add("”Ã· «·“»«∆‰ ",new AgentMenu());
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
