/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aboud.gradleproject1;

//import static com.aboud.gradleproject1.ViewOfdata.model2;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.MessageFormat;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;

import com.itextpdf.text.pdf.PdfWriter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aboud Mahmoud
 */
public class BillPrinter extends javax.swing.JPanel {

    /**
     * Creates new form BillPrinter
     */
    private String[] headr = {" «”„ «·⁄„Ì·", "›—⁄ «· Õ’Ì·", "—ﬁ„ «·„⁄—› ", "”⁄— «·ÿ—œ"};
    private String[][] dater;
    private ArrayList<BillValue> arr;
    static DefaultTableModel model2 = new DefaultTableModel();

    public BillPrinter() throws MalformedURLException {
        initComponents();
        getTheFullInfo();
        imageSater();
    }

    void imageSater() throws MalformedURLException {
      
        ImageIcon myimage = setIMAgeFor("https://firebasestorage.googleapis.com/v0/b/projectmangment-666fb.appspot.com/o/refresh.png?alt=media&token=d5751ad7-6538-439b-8ee3-f930b71edab5");
        jButton3.setIcon(myimage);
        
       myimage =setIMAgeFor("https://firebasestorage.googleapis.com/v0/b/projectmangment-666fb.appspot.com/o/printer.png?alt=media&token=b06151e4-ccb9-4d82-a58b-f4d305101e3e");
        jButton1.setIcon(myimage);
      
        myimage = setIMAgeFor("https://firebasestorage.googleapis.com/v0/b/projectmangment-666fb.appspot.com/o/slide-show.png?alt=media&token=e561cd2a-c39c-4552-9c09-bdf7557055c9");
        jButton2.setIcon(myimage);
    }
    
     private ImageIcon setIMAgeFor(String path) throws MalformedURLException {
        URL urt = new URL(path);
        Image iconr = Toolkit.getDefaultToolkit().getImage(urt);
        ImageIcon myimage = new ImageIcon(iconr);
        return myimage;
    }

    void getTheFullInfo() {
        arr = LiteConection.getThe_Bill();
        dater = new String[arr.size()][4];
        for (int i = 0; i < arr.size(); i++) {
            dater[i][0] = arr.get(i).getCousmterName();
            dater[i][1] = arr.get(i).getDaprmentChcker();
            dater[i][2] = "" + arr.get(i).getID();
            dater[i][3] = arr.get(i).getBillPrice();

        }
        jTable1 = new JTable(dater, headr);

        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment((int) JLabel.CENTER_ALIGNMENT);
        DefaultTableCellRenderer v = new DefaultTableCellRenderer();
        v.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(v);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(v);
        }
        jScrollPane1.setViewportView(jTable1);

    }

    void SetIamgeBakge() {

        int col = 0;
        int row = jTable1.getSelectedRow();
        String Name = jTable1.getModel().getValueAt(row, col).toString();
        arr = LiteConection.getThe_Bill();
        ArrayList<PackgeValue> ar = LiteConection.getPackgeInfo();
        for (int i = 0; i < arr.size(); i++) {
            if (arr.get(i).getCousmterName().equals(Name)) {
                jLabel2.setIcon(SetImagesiz(ar.get(i).getPackgeImagePath()));
                jLabel2.setText(null);
                jPanel2.setBackground(Color.WHITE);
            }

        }
    }

    public ImageIcon SetImagesiz(String imagePathe) {
        ImageIcon myimage = new ImageIcon(imagePathe);
        Image img = myimage.getImage();
        Image amg = img.getScaledInstance(96, 100, java.awt.Image.SCALE_SMOOTH);
        ImageIcon imr = new ImageIcon(amg);
        return imr;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(38, 70, 83));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("«·›« Ê—…");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(42, 157, 143));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ÿ»«⁄…");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("«·’Ê—… €Ì— „ÊÃÊœÂ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("’Ê—… «·ÿ—œ:");

        jButton2.setBackground(new java.awt.Color(42, 157, 143));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("«ŸÂ— «·’Ê—… ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(42, 157, 143));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText(" ÕœÌÀ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SetIamgeBakge();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
              int col = 0;
            int row = jTable1.getSelectedRow();
            
           ArrayList<PackgeValue> arr2 = LiteConection.getPackgeInfo();
            dater = new String[arr2.size()][10];
            String Name = jTable1.getModel().getValueAt(row, col).toString();
            for (int rt = 0; rt < arr2.size(); rt++) {
            if (arr2.get(rt).getOwnerPackageName().equals(Name)) {
           /* dater[rt][0] = arr.get(rt).getCousmterName();
            dater[rt][1] = arr.get(rt).getDaprmentChcker();
            dater[rt][2] = "" + arr.get(rt).getID();
            dater[rt][3] = arr.get(rt).getBillPrice();*/
            new PrintedrClass(Name,arr2.get(rt).getPackgeDamperntHolder(),arr2.get(rt).getPackgePrice(),arr2.get(rt).getOwnerPhoneNumber(),arr2.get(rt).getPackgeNote(),arr2.get(rt).getOwnerFacount());
            break;
            
            }
            
            }
           
            
        } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (DocumentException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            MangmentPage.jTabbedPane2.remove(this);
            MangmentPage.jTabbedPane2.add(new BillPrinter(), "›Ê« Ì— «·⁄„·«¡");
        } catch (MalformedURLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
