/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aboud.gradleproject1;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aboud Mahmoud
 */
public class RequstesOrder extends javax.swing.JPanel {

    /**
     * Creates new form RequstesOrder
     */
     private  String[] headr= {"„Â„Â", " Ê’› «·„Â„Â ", "  «—ÌŒ «‰Â«¡ «·„Â„Â"};
     private String[][] dater;
         static DefaultTableModel model = new DefaultTableModel();

    public RequstesOrder() throws MalformedURLException {
        initComponents();
        getReqstedData();
        imageSater();
    }
     void imageSater() throws MalformedURLException {
        
        ImageIcon myimage = setIMAgeFor("https://firebasestorage.googleapis.com/v0/b/projectmangment-666fb.appspot.com/o/add.png?alt=media&token=95d06bab-7a29-4c39-b441-82b1d73aa7f4");
        jButton1.setIcon(myimage);
    
        myimage = setIMAgeFor("https://firebasestorage.googleapis.com/v0/b/projectmangment-666fb.appspot.com/o/delete.png?alt=media&token=e6b21083-1907-4a24-ba6e-3726ac809fdc");
        jButton2.setIcon(myimage);
      
    }
     
      private ImageIcon setIMAgeFor(String path) throws MalformedURLException
     {
         URL urt= new URL(path);
         Image iconr = Toolkit.getDefaultToolkit().getImage(urt);
          ImageIcon myimage = new ImageIcon(iconr);
          return myimage;
     }

    void getReqstedData()
    {
        ArrayList<RequstedValue> arr=LiteConection.getRequsted(); 
         dater = new String[arr.size()][3];
         for (int i=0 ; i<arr.size(); i++)
         {
             dater[i][2]=arr.get(i).getRequstDate();
             dater[i][1]=arr.get(i).getRequstDiscrabtion();
             dater[i][0]=arr.get(i).getRequstsorder();
         }
           jTable1=new JTable(dater,headr);
       
          //jScrollPane1.setLayout(null);
           
             ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer())
             .setHorizontalAlignment((int)JLabel.CENTER_ALIGNMENT);
     DefaultTableCellRenderer v = new DefaultTableCellRenderer();
     v.setHorizontalAlignment(JLabel.CENTER);
     jTable1.getColumnModel().getColumn(0).setCellRenderer(v);
     for( int i=0 ; i<jTable1.getColumnCount();i++)
     {
         jTable1.getColumnModel().getColumn(i).setCellRenderer(v);
     }
      jScrollPane1.setViewportView(jTable1);
        
    }
    
    void InsertReqstData()
    { 
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        
        LiteConection.insert_Requste(t1.getText(), t2.getText(),formatter.format(t3.getDate()).toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        t3 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 70, 83));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("«÷«›… „Â„Â ÃœÌœÂ");

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ê’› «·„Â„Â");

        t2.setColumns(20);
        t2.setRows(5);
        jScrollPane2.setViewportView(t2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ﬁ«∆„… «·„Â„« ");

        jButton1.setBackground(new java.awt.Color(42, 157, 143));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("«÷«›… «·„Â„Â");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(231, 111, 81));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Õ–› „Â„Â");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" «—ÌŒ «·«‰ Â«¡ „‰ «·„Â„Â");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane2)
                                    .addComponent(t1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        InsertReqstData();
        t1.setText(null);
        t2.setText(null);
        t3.setCalendar(null);
        RefRach();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
             // TODO add your handling code here:
             
             if(  jTable1.getSelectedRow() > 0 )
             {
                 // «·Œ«’ ›ÌÂ index ﬂ· ”ÿ— ﬁ«„ «·„” Œœ„ » ÕœÌœÂ „‰ «·ÃœÊ· »⁄œÂ« ”Ì „ Õ–› ﬂ· ”ÿ— „‰ Œ·«· —ﬁ„ «·‹ index ”Ì „  Œ“Ì‰ —ﬁ„
                 int[] selectedIndices =  jTable1.getSelectedRows();
                 for( int i=selectedIndices.length-1; i>0; i-- )
                 {
                     model.removeRow( selectedIndices[i] );
                 }
             }
             int col= 0;
             int row=jTable1.getSelectedRow();
             String Rr=jTable1.getModel().getValueAt(row, col).toString();
             LiteConection.deletReqsted(Rr);
             RefRach();
         } catch (MalformedURLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

void RefRach() throws MalformedURLException
{
     MangmentPage.jTabbedPane2.remove(this);
        MangmentPage.jTabbedPane2.add(new RequstesOrder(),"«·„Â„« ");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea t2;
    private com.toedter.calendar.JDateChooser t3;
    // End of variables declaration//GEN-END:variables
}
